apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-worker-service
  namespace: prioriza
  labels:
    app: prioriza
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: prioriza
      kind: worker
  template:
    metadata:
      labels:
        app: prioriza
        kind: worker
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox
          command:
            - sh
            - -c
            - |
              until nslookup db-redis-service.prioriza.svc.cluster.local > /dev/null; do
                echo waiting for redis...
                sleep 2
              done
        - name: wait-for-rabbit
          image: busybox
          command:
            - sh
            - -c
            - |
              until nslookup mq-rabbit-service.prioriza.svc.cluster.local > /dev/null; do
                echo waiting for rabbit...
                sleep 2
              done
      containers:
        - name: worker
          image: nyyakko/prioriza-stock-worker-service:latest
          envFrom:
            - configMapRef:
                name: backend-config
                optional: false
status: {}
